apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rating-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: bookinfo-rating-config-test
spec:
  git:
    type: github
    apiUrl: ""
    repository: changju-test/bookinfo-rating
    token:
      valueFrom:
        secretKeyRef:
          name: git-token
          key: token
  workspaces:
    - name : rating-workspace
      persistentVolumeClaim:
        claimName: rating-pvc
  secrets:
    - name : tmaxcloudck-docker-hub-secret
  jobs:
    postSubmit:
      - name: git-clone
        image: docker.io/alpine/git
        script: |
          set -x
          set -e

          git config --global user.email "bot@cicd.tmax.io"
          git config --global user.name "tmax-cicd-bot"
          git init

          CHECKOUT_URL="$CI_SERVER_URL/$CI_REPOSITORY"
          CI_HEAD_REF_ARRAY="$CI_HEAD_REF"

          if [ "$CI_BASE_REF" = "" ]; then 
            # Push Event
            CHECKOUT_REF="$CI_HEAD_REF"
          else 
            # Pull Request Event
            CHECKOUT_REF="$CI_BASE_REF"
          fi

          git fetch "$CHECKOUT_URL" "$CHECKOUT_REF"
          git checkout FETCH_HEAD

          if [ "$CI_BASE_REF" != "" ]; then
            # Pull request event
            for ci_head_ref in $CI_HEAD_REF_ARRAY; do 
              git fetch "$CHECKOUT_URL" "$ci_head_ref"
              git merge --no-ff FETCH_HEAD
            done
          fi

          git submodule update --init --recursive
          
          cp -r ./ $(workspaces.rating-workspace.path)/git-clone
        skipCheckout: true
      - name: copy-source
        image: docker.io/alpine:3.13.6
        script: |
          cp -r $(workspaces.rating-workspace.path)/git-clone ./
          ls -al
        skipCheckout: true
        after:
          - git-clone
#      - name: s2i-gradle-generate
#        image: docker.io/tmaxcloudck/cicd-util:5.0.5
#        env:
#          - name: JAR_NAME
#            value : rating.jar
#        script: |
#          /usr/local/bin/s2i \
#          build . docker.io/changjjjjjjjj/s2i-gradle-java:dev \
#          --env JAR_NAME=$JAR_NAME \
#          --tlsverify=false \
#        skipCheckout: true