apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rating-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: bookinfo-rating-config-test
spec:
  git:
    type: github
    apiUrl: ""
    repository: changju-test/bookinfo-rating
    token:
      valueFrom:
        secretKeyRef:
          name: git-token
          key: token
  workspaces:
    - name : rating-workspace
      persistentVolumeClaim:
        claimName: rating-pvc
  secrets:
    - name : tmaxcloudck-docker-hub-secret
  jobs:
    postSubmit:
      - name: gradle-build-and-publish
        image: docker.io/gradle:7.3.1-jdk11
        script: |
          gradle build
          gradle sonarqube
          gradle publish
